name: Pipeline

on:
    pull_request:
    push:
        branches: ["*"]
        paths:
            - "configuration/"
            - "Dockerfile"
            - "*.sh"
            - ".github/workflows/**"
    repository_dispatch:

jobs:
    # update:
    #     name: Auto-commit updates to submodules
    #     runs-on: ubuntu-latest
    #
    #     permissions:
    #         contents: write
    #
    #     steps:
    #         - uses: actions/checkout@v4
    #           name: Checkout repository
    #           with:
    #               ref: ${{ github.head_ref }}
    #               fetch-depth: 0
    #               submodules: "recursive"
    #
    #         - name: Update submodules to latest
    #           run: |
    #             git submodule update --remote --merge
    #
    #         - uses: stefanzweifel/git-auto-commit-action@v5
    #           name: Commit updated submodules
    #           with:
    #             commit_message: Update to latest
    #             commit_author: cyrus01337
    #             commit_user_name: cyrus01337
    #             commit_user_email: ${{ secrets.COMMIT_USER_EMAIL }}

    publish:
        name: Publish to Docker Hub
        runs-on: ubuntu-latest
        needs: update

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
                  submodules: "recursive"

            - name: Extract project metadata
              env:
                  AUTHOR: ${{ vars.DOCKER_HUB_USERNAME }}
                  GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
              run: |
                  declare -a split_by_slash=()

                  IFS="/" read -ra split_by_slash <<< "$GITHUB_REPOSITORY"

                  REAL_AUTHOR=${AUTHOR:-${split_by_slash[0]}}

                  echo "AUTHOR=$REAL_AUTHOR" >> "$GITHUB_ENV"
                  echo "TAG=$REAL_AUTHOR/neovim-devcontainer" >> "$GITHUB_ENV"

            - uses: docker/setup-buildx-action@v3
              name: Setup Docker Buildx

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.AUTHOR }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Publish Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ env.TAG }}

